// Zelda fangame client -- SDL3 + OpenGL 3.3 core.
// Milestone 1: skinned Link from assets/link.glb, all clips playable.
//   left/right : switch animation clip
//   drag       : orbit camera   wheel : zoom
//   esc        : quit
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include "clef_glyph.h"
#include "gl_loader.h"
#include "math3d.h"
#include "model.h"
#include "player.h"

namespace {

constexpr int kWindowWidth = 1280;
constexpr int kWindowHeight = 720;
constexpr double kFixedDt = 1.0 / 60.0;
#ifdef EMBED_LINK_GLB
extern "C" {
extern unsigned char g_link_glb[];       // generated by cmake/bin2c.cmake
extern unsigned long long g_link_glb_size;
}
#endif

constexpr Vec3 kTargetPos{0.0f, 0.35f, 4.0f};  // the lock-on cube
constexpr float kTargetHalf = 0.35f;     // the cube's half-extent (bounding size)
constexpr float kLockMaxOffset = 0.22f;  // lock-on camera's max off-axis angle

const char* kSkinVS = R"GLSL(
#version 330 core
layout(location=0) in vec3 aPos;
layout(location=1) in vec3 aNormal;
layout(location=2) in vec2 aUV;
layout(location=3) in uvec4 aJoints;
layout(location=4) in vec4 aWeights;

uniform mat4 uViewProj;
uniform mat4 uModel;
uniform mat4 uPalette[64];

out vec3 vNormal;
out vec2 vUV;

void main() {
    mat4 skin = aWeights.x * uPalette[aJoints.x]
              + aWeights.y * uPalette[aJoints.y]
              + aWeights.z * uPalette[aJoints.z]
              + aWeights.w * uPalette[aJoints.w];
    vec4 world = uModel * skin * vec4(aPos, 1.0);
    vNormal = normalize(mat3(uModel) * mat3(skin) * aNormal);
    vUV = aUV;
    gl_Position = uViewProj * world;
}
)GLSL";

const char* kSkinFS = R"GLSL(
#version 330 core
in vec3 vNormal;
in vec2 vUV;
uniform sampler2D uTex;
uniform vec3 uSunDir;
out vec4 fragColor;

void main() {
    vec4 albedo = texture(uTex, vUV);
    // ramp the filtered alpha so decal edges (eyebrows) stay smooth but sharp
    albedo.a = smoothstep(0.35, 0.65, albedo.a);
    if (albedo.a < 0.01) discard;
    float ndl = max(dot(normalize(vNormal), -uSunDir), 0.0);
    // two-band toon shading
    float light = ndl > 0.35 ? 1.0 : 0.72;
    fragColor = vec4(albedo.rgb * light, albedo.a);
}
)GLSL";

const char* kCubeVS = R"GLSL(
#version 330 core
layout(location=0) in vec3 aPos;
layout(location=1) in float aShade;
uniform mat4 uViewProj;
out float vShade;
void main() { vShade = aShade; gl_Position = uViewProj * vec4(aPos, 1.0); }
)GLSL";

const char* kCubeFS = R"GLSL(
#version 330 core
in float vShade;
out vec4 fragColor;
void main() { fragColor = vec4(vec3(0.75, 0.45, 0.25) * vShade, 1.0); }
)GLSL";

const char* kReticleVS = R"GLSL(
#version 330 core
layout(location=0) in vec3 aPos;
uniform mat4 uViewProj;
uniform vec3 uCenter;
uniform float uSpin;
uniform float uScale;
void main() {
    float c = cos(uSpin), s = sin(uSpin);
    vec3 p = vec3(aPos.x * c - aPos.z * s, aPos.y, aPos.x * s + aPos.z * c) * uScale;
    gl_Position = uViewProj * vec4(p + uCenter, 1.0);
}
)GLSL";

const char* kReticleFS = R"GLSL(
#version 330 core
uniform float uAlpha;
out vec4 fragColor;
void main() { fragColor = vec4(1.0, 0.85, 0.25, uAlpha); }
)GLSL";

const char* kWindVS = R"GLSL(
#version 330 core
layout(location=0) in vec3 aPos;
layout(location=1) in float aAlpha;
uniform mat4 uViewProj;
out float vA;
void main() { vA = aAlpha; gl_Position = uViewProj * vec4(aPos, 1.0); }
)GLSL";

const char* kWindFS = R"GLSL(
#version 330 core
in float vA;
out vec4 fragColor;
void main() { fragColor = vec4(0.94, 0.98, 1.0, vA); }
)GLSL";

// --- 2D HUD: flat colour triangles in a virtual 1280x720 space, y down ---
const char* kHudVS = R"GLSL(
#version 330 core
layout(location=0) in vec2 aPos;
layout(location=1) in vec4 aCol;
uniform vec3 uScreen;   // vec3: the loader only exposes glUniform3fv
out vec4 vCol;
void main() {
    vCol = aCol;
    vec2 p = aPos / uScreen.xy * 2.0 - 1.0;
    gl_Position = vec4(p.x, -p.y, 0.0, 1.0);
}
)GLSL";

const char* kHudFS = R"GLSL(
#version 330 core
in vec4 vCol;
out vec4 fragColor;
void main() { fragColor = vCol; }
)GLSL";

const char* kHudTexVS = R"GLSL(
#version 330 core
layout(location=0) in vec2 aPos;
layout(location=1) in vec2 aUV;
uniform vec3 uScreen;
out vec2 vUV;
void main() {
    vUV = aUV;
    vec2 p = aPos / uScreen.xy * 2.0 - 1.0;
    gl_Position = vec4(p.x, -p.y, 0.0, 1.0);
}
)GLSL";

const char* kHudTexFS = R"GLSL(
#version 330 core
in vec2 vUV;
uniform sampler2D uTex;
uniform vec4 uColor;
out vec4 fragColor;
void main() { fragColor = vec4(uColor.rgb, uColor.a * texture(uTex, vUV).a); }
)GLSL";

// 5x7 glyphs, one byte per column, bit 0 = top row. Only the characters the
// ocarina prompt needs.
struct Glyph { char c; unsigned char col[5]; };
const Glyph kFont[] = {
    {' ', {0x00, 0x00, 0x00, 0x00, 0x00}},
    {',', {0x00, 0x50, 0x30, 0x00, 0x00}},
    {'.', {0x00, 0x60, 0x60, 0x00, 0x00}},
    {'!', {0x00, 0x00, 0x5F, 0x00, 0x00}},
    {'#', {0x14, 0x7F, 0x14, 0x7F, 0x14}},   // sharp
    {'b', {0x7F, 0x48, 0x44, 0x44, 0x38}},   // flat
    {'B', {0x7F, 0x49, 0x49, 0x49, 0x36}},
    {'C', {0x3E, 0x41, 0x41, 0x41, 0x22}},
    {'E', {0x7F, 0x49, 0x49, 0x49, 0x41}},
    {'F', {0x7F, 0x09, 0x09, 0x09, 0x01}},
    {'H', {0x7F, 0x08, 0x08, 0x08, 0x7F}},
    {'M', {0x7F, 0x02, 0x0C, 0x02, 0x7F}},
    {'O', {0x3E, 0x41, 0x41, 0x41, 0x3E}},
    {'T', {0x01, 0x01, 0x7F, 0x01, 0x01}},
    {'V', {0x1F, 0x20, 0x40, 0x20, 0x1F}},
    {'W', {0x3F, 0x40, 0x38, 0x40, 0x3F}},
    {'A', {0x7E, 0x11, 0x11, 0x11, 0x7E}},
    {'D', {0x7F, 0x41, 0x41, 0x22, 0x1C}},
    {'G', {0x3E, 0x41, 0x49, 0x49, 0x7A}},
    {'I', {0x00, 0x41, 0x7F, 0x41, 0x00}},
    {'K', {0x7F, 0x08, 0x14, 0x22, 0x41}},
    {'L', {0x7F, 0x40, 0x40, 0x40, 0x40}},
    {'N', {0x7F, 0x04, 0x08, 0x10, 0x7F}},
    {'P', {0x7F, 0x09, 0x09, 0x09, 0x06}},
    {'R', {0x7F, 0x09, 0x19, 0x29, 0x46}},
    {'S', {0x46, 0x49, 0x49, 0x49, 0x31}},
    {'U', {0x3F, 0x40, 0x40, 0x40, 0x3F}},
    {'X', {0x63, 0x14, 0x08, 0x14, 0x63}},
    {'Y', {0x07, 0x08, 0x70, 0x08, 0x07}},
};

const char* kStarVS = R"GLSL(
#version 330 core
layout(location=0) in vec3 aPos;
layout(location=1) in vec2 aUV;
layout(location=2) in float aAlpha;
uniform mat4 uViewProj;
out vec2 vUV;
out float vA;
void main() {
    vUV = aUV;
    vA = aAlpha;
    gl_Position = uViewProj * vec4(aPos, 1.0);
}
)GLSL";

// four-pointed sparkle: an astroid falloff, no texture needed
const char* kStarFS = R"GLSL(
#version 330 core
in vec2 vUV;
in float vA;
out vec4 fragColor;
void main() {
    vec2 p = vUV * 2.0 - 1.0;
    float d = pow(abs(p.x), 0.5) + pow(abs(p.y), 0.5);
    // note: smoothstep needs edge0 < edge1 -- reversed edges are undefined
    // and come back as 0 on some drivers, which makes the whole star vanish
    float a = 1.0 - smoothstep(0.25, 1.0, d);
    float core = 1.0 - smoothstep(0.0, 0.55, length(p));
    fragColor = vec4(1.0, 0.96, 0.70, (a * 0.85 + core * 0.6) * vA);
}
)GLSL";

const char* kGridVS = R"GLSL(
#version 330 core
layout(location=0) in vec3 aPos;
uniform mat4 uViewProj;
out vec3 vWorld;
void main() { vWorld = aPos; gl_Position = uViewProj * vec4(aPos, 1.0); }
)GLSL";

const char* kGridFS = R"GLSL(
#version 330 core
in vec3 vWorld;
out vec4 fragColor;
void main() {
    vec2 g = abs(fract(vWorld.xz - 0.5) - 0.5) / fwidth(vWorld.xz);
    float line = 1.0 - min(min(g.x, g.y), 1.0);
    vec3 base = vec3(0.16, 0.32, 0.20);
    fragColor = vec4(mix(base, vec3(0.24, 0.44, 0.28), line), 1.0);
}
)GLSL";

GLuint compile_shader(GLenum type, const char* src)
{
    GLuint s = glCreateShader(type);
    glShaderSource(s, 1, &src, nullptr);
    glCompileShader(s);
    GLint ok = 0;
    glGetShaderiv(s, GL_COMPILE_STATUS, &ok);
    if (!ok) {
        char log[2048];
        glGetShaderInfoLog(s, sizeof(log), nullptr, log);
        SDL_Log("shader compile error:\n%s", log);
        return 0;
    }
    return s;
}

GLuint link_program(const char* vs_src, const char* fs_src)
{
    GLuint vs = compile_shader(GL_VERTEX_SHADER, vs_src);
    GLuint fs = compile_shader(GL_FRAGMENT_SHADER, fs_src);
    if (!vs || !fs) return 0;
    GLuint p = glCreateProgram();
    glAttachShader(p, vs);
    glAttachShader(p, fs);
    glLinkProgram(p);
    glDeleteShader(vs);
    glDeleteShader(fs);
    GLint ok = 0;
    glGetProgramiv(p, GL_LINK_STATUS, &ok);
    if (!ok) {
        char log[2048];
        glGetProgramInfoLog(p, sizeof(log), nullptr, log);
        SDL_Log("program link error:\n%s", log);
        return 0;
    }
    return p;
}

struct OrbitCamera {
    float yaw = 0.6f;       // radians around the character
    float pitch = 0.35f;
    float distance = 5.6f;
    Vec3 target{0.0f, 0.85f, 0.0f};

    // up-arrow "overview": almost pure pull-back, only a whisper of rotation
    float pull = 0.0f;
    static constexpr float kDefaultPitch = 0.35f;

    Vec3 eye() const
    {
        // the whisper of rotation rides the pull itself, so zoom-out and
        // tilt are one continuous motion (and reverse together)
        // pulling out is a pure dolly; the low end couples downward tilt
        const float p = pitch + (pull > 0.0f ? 0.0f : pull * 0.025f);
        const float cp = std::cos(p);
        return target + Vec3{cp * std::sin(yaw), std::sin(p), cp * std::cos(yaw)} * (distance + pull);
    }
};

struct App {
    SDL_Window* window = nullptr;
    SDL_GLContext gl = nullptr;
    bool running = true;
    double sim_time = 0.0;

    Model link;
    int clip_index = 0;
    double clip_time = 0.0;
    OrbitCamera cam;
    bool dragging = false;

    Player player;
    float lock_blend = 0.0f;   // eased 0..1 lock-on camera engagement
    float free_yaw = 0.6f;     // camera angle to restore after lock-on
    float free_pitch = 0.35f;
    bool was_locked = false;
    bool lock_cam_manual = false;  // user orbited during lock: stop auto-framing
    float cam_arc = 0.0f;   // -1..1 vertical sweep: ground angle .. pulled-out
    float orbit_vel = 0.0f;  // arrow-orbit yaw velocity (eases out on release)
    float lock_offset = 0.22f;  // off-axis angle while locked, orbit-driven,
                                // clamped to +-kLockMaxOffset (runs out of travel)
    bool viewer_mode = false;  // F1: clip viewer (arrow keys) vs play mode
    SDL_Gamepad* pad = nullptr;
    bool key_attack = false, key_roll = false;  // edge flags for this sim step
    bool key_flute = false, key_sheathe = false;
};

bool save_screenshot(const char* path, int fb_w, int fb_h)
{
    std::vector<uint8_t> pixels(static_cast<size_t>(fb_w) * fb_h * 4);
    glPixelStorei(GL_PACK_ALIGNMENT, 1);
    glReadPixels(0, 0, fb_w, fb_h, GL_RGBA, GL_UNSIGNED_BYTE, pixels.data());
    // GL reads bottom-up; flip rows
    std::vector<uint8_t> flipped(pixels.size());
    const size_t row = static_cast<size_t>(fb_w) * 4;
    for (int y = 0; y < fb_h; ++y)
        std::memcpy(&flipped[row * y], &pixels[row * (fb_h - 1 - y)], row);
    SDL_Surface* surf = SDL_CreateSurfaceFrom(fb_w, fb_h, SDL_PIXELFORMAT_ABGR8888,
                                              flipped.data(), static_cast<int>(row));
    if (!surf) return false;
    const bool ok = SDL_SaveBMP(surf, path);
    SDL_DestroySurface(surf);
    SDL_Log("screenshot %s: %s", path, ok ? "saved" : SDL_GetError());
    return ok;
}

void set_title(App& app, Uint64 fps)
{
    char title[160];
    if (app.viewer_mode) {
        const std::string clip =
            app.link.clips.empty() ? "none" : app.link.clips[app.clip_index].name;
        std::snprintf(title, sizeof(title),
                      "Zelda Fangame [viewer]  clip: %s (left/right)  |  %llu fps",
                      clip.c_str(), static_cast<unsigned long long>(fps));
    } else {
        std::snprintf(title, sizeof(title),
                      "Zelda Fangame  WASD move, space roll, J attack, shift guard, "
                      "F1 viewer  |  %llu fps",
                      static_cast<unsigned long long>(fps));
    }
    SDL_SetWindowTitle(app.window, title);
}

}  // namespace

int main(int argc, char** argv)
{
    // --screenshot <path> [clip] [time] [distance] : render one frame, save, exit
    const char* shot_path = nullptr;
    const char* shot_clip = "Idle";
    float shot_time = 0.5f;
    float shot_distance = 0.0f;
    float shot_yaw = 1000.0f;  // sentinel = keep default
    for (int i = 1; i < argc; ++i) {
        if (std::string(argv[i]) == "--screenshot" && i + 1 < argc) {
            shot_path = argv[i + 1];
            if (i + 2 < argc) shot_clip = argv[i + 2];
            if (i + 3 < argc) shot_time = static_cast<float>(std::atof(argv[i + 3]));
            if (i + 4 < argc) shot_distance = static_cast<float>(std::atof(argv[i + 4]));
            if (i + 5 < argc) shot_yaw = static_cast<float>(std::atof(argv[i + 5]));
        }
    }

    if (!SDL_Init(SDL_INIT_VIDEO | SDL_INIT_GAMEPAD | SDL_INIT_AUDIO)) {
        SDL_Log("SDL_Init failed: %s", SDL_GetError());
        return 1;
    }

    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
    SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);

    App app;
    app.window = SDL_CreateWindow("Zelda Fangame", kWindowWidth, kWindowHeight,
                                  SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE |
                                  SDL_WINDOW_HIGH_PIXEL_DENSITY);
    if (!app.window) {
        SDL_Log("SDL_CreateWindow failed: %s", SDL_GetError());
        return 1;
    }
    app.gl = SDL_GL_CreateContext(app.window);
    if (!app.gl || !gl_load_functions()) {
        SDL_Log("GL context/loader failed: %s", SDL_GetError());
        return 1;
    }
    SDL_GL_SetSwapInterval(1);
    SDL_Log("GL_VERSION:  %s", reinterpret_cast<const char*>(glGetString(GL_VERSION)));

    // asset path: exe dir /../../assets (build/Debug/zelda.exe) with cwd fallback
#ifdef EMBED_LINK_GLB
    if (!app.link.load_memory(g_link_glb, static_cast<size_t>(g_link_glb_size))) {
        SDL_Log("could not load embedded link.glb");
#else
    std::string glb = std::string(SDL_GetBasePath()) + "..\\..\\assets\\link.glb";
    if (!app.link.load(glb.c_str()) && !app.link.load("assets/link.glb")) {
        SDL_Log("could not load link.glb");
#endif
        return 1;
    }
    if (const AnimClip* idle = app.link.find_clip("Idle"))
        app.clip_index = static_cast<int>(idle - app.link.clips.data());

    // --- shield sockets: sheath (as authored) and forearm (computed from the
    // guard stance: keep the sheathed orientation but spin it to face front,
    // planted ahead of the chest, then expressed relative to the forearm) ---
    Model::Attachment shield_sheath{};
    Model::Attachment shield_arm{};
    // guard placement tunables (viewer mode, or in game while guarding:
    // I/K height, J/L sideways, U/O depth, [/] roll, ,/. pitch; persisted to
    // guard_tune.txt next to the exe so the winners can be baked in here)
    float guard_x = -0.10f, guard_y = 0.80f, guard_z = 0.44f, guard_roll = -0.48f;
    float guard_pitch = 0.06f, guard_yaw = 0.0f;
    const std::string guard_tune_path = std::string(SDL_GetBasePath()) + "guard_tune.txt";
    if (FILE* tf = std::fopen(guard_tune_path.c_str(), "r")) {
        float v[6] = {0, 0, 0, 0, 0, 0};
        const int n = std::fscanf(tf, "%f %f %f %f %f %f",
                                  &v[0], &v[1], &v[2], &v[3], &v[4], &v[5]);
        if (n >= 5) {  // yaw column added later; old 5-value files still load
            guard_x = v[0]; guard_y = v[1]; guard_z = v[2];
            guard_roll = v[3]; guard_pitch = v[4];
            if (n == 6) guard_yaw = v[5];
            SDL_Log("guard_tune.txt loaded: x=%.3f y=%.3f z=%.3f roll=%.3f pitch=%.3f yaw=%.3f",
                    guard_x, guard_y, guard_z, guard_roll, guard_pitch, guard_yaw);
        }
        std::fclose(tf);
    }
    auto save_guard_tune = [&]() {
        if (FILE* tf = std::fopen(guard_tune_path.c_str(), "w")) {
            std::fprintf(tf, "%.4f %.4f %.4f %.4f %.4f %.4f\n", guard_x, guard_y,
                         guard_z, guard_roll, guard_pitch, guard_yaw);
            std::fclose(tf);
        }
    };
    save_guard_tune();  // file exists from the first run on; nothing gets lost

    // relaxed in-hand placement (idle/run once the shield has been raised):
    // its own socket + tune file, adjusted on any non-Guard clip in the viewer
    float hand_x = -0.40f, hand_y = 0.39f, hand_z = 0.12f;
    float hand_roll = -1.80f, hand_pitch = -0.08f, hand_yaw = -1.58f;
    const std::string hand_tune_path = std::string(SDL_GetBasePath()) + "hand_tune.txt";
    if (FILE* tf = std::fopen(hand_tune_path.c_str(), "r")) {
        float v[6] = {0, 0, 0, 0, 0, 0};
        const int n = std::fscanf(tf, "%f %f %f %f %f %f",
                                  &v[0], &v[1], &v[2], &v[3], &v[4], &v[5]);
        if (n >= 5) {
            hand_x = v[0]; hand_y = v[1]; hand_z = v[2];
            hand_roll = v[3]; hand_pitch = v[4];
            if (n == 6) hand_yaw = v[5];
        }
        std::fclose(tf);
    }
    auto save_hand_tune = [&]() {
        if (FILE* tf = std::fopen(hand_tune_path.c_str(), "w")) {
            std::fprintf(tf, "%.4f %.4f %.4f %.4f %.4f %.4f\n", hand_x, hand_y, hand_z,
                         hand_roll, hand_pitch, hand_yaw);
            std::fclose(tf);
        }
    };
    save_hand_tune();

    // vertical-arc camera tunables (game mode: F5/F6 rotation cap -/+,
    // F7/F8 zoom-out max -/+), persisted like the shield tuning
    float cam_rot_cap = -0.07f;  // top-of-sweep angle offset from the default
    float cam_zoom_max = 4.6f;   // pull-out distance at full arc
    const std::string cam_tune_path = std::string(SDL_GetBasePath()) + "cam_tune.txt";
    if (FILE* tf = std::fopen(cam_tune_path.c_str(), "r")) {
        float v[2];
        if (std::fscanf(tf, "%f %f", &v[0], &v[1]) == 2) {
            cam_rot_cap = v[0];
            cam_zoom_max = v[1];
        }
        std::fclose(tf);
    }
    auto save_cam_tune = [&]() {
        if (FILE* tf = std::fopen(cam_tune_path.c_str(), "w")) {
            std::fprintf(tf, "%.4f %.4f\n", cam_rot_cap, cam_zoom_max);
            std::fclose(tf);
        }
    };
    save_cam_tune();
    Mat4 guard_sheath_world{};
    Mat4 guard_forearm_inv{};
    Mat4 hand_sheath_world{};
    Mat4 hand_forearm_inv{};
    Model::Attachment shield_hand{};
    bool guard_socket_valid = false;
    bool shield_in_hand = false;  // set the first time the guard comes up
    if (Model::Attachment* sh = app.link.find_attachment("Shield")) {
        shield_sheath = *sh;
        const int forearm = app.link.find_node("RarmB_jnt_bone_id");
        if (const AnimClip* guard_clip = app.link.find_clip("Guard");
            guard_clip && forearm >= 0) {
            // replicate the RUNTIME pose: idle base with the guard overlay's
            // rotations on the upper body (what the player actually shows)
            app.link.sample(*app.link.find_clip("Idle"), 0.5f, app.link.scratch_a);
            app.link.sample(*guard_clip, guard_clip->start + 0.2f, app.link.scratch_b);
            const std::vector<uint8_t> upper = app.link.subtree_mask("Root");
            for (size_t i = 0; i < app.link.scratch_a.size(); ++i) {
                if (i < upper.size() && upper[i]) {
                    app.link.scratch_a[i].r = app.link.scratch_b[i].r;
                    app.link.scratch_a[i].s = app.link.scratch_b[i].s;
                }
            }
            app.link.palette_from(app.link.scratch_a);  // fills world_pose
            guard_sheath_world =
                app.link.world_pose[shield_sheath.anchor_node] * shield_sheath.offset;
            guard_forearm_inv = mat4_inverse(app.link.world_pose[forearm]);
            shield_arm.name = shield_sheath.name;
            shield_arm.slot = shield_sheath.slot;
            shield_arm.anchor_node = forearm;
            guard_socket_valid = true;

            // relaxed socket: same construction against the plain idle pose
            app.link.sample(*app.link.find_clip("Idle"), 0.5f, app.link.scratch_a);
            app.link.palette_from(app.link.scratch_a);
            hand_sheath_world =
                app.link.world_pose[shield_sheath.anchor_node] * shield_sheath.offset;
            hand_forearm_inv = mat4_inverse(app.link.world_pose[forearm]);
            shield_hand = shield_arm;
        }
    }
    // face it forward (Y-flip), cancel the sheath's slant so it stands
    // straight on the arm, then plant it at the tuned spot
    auto rebuild_guard_socket = [&]() {
        if (!guard_socket_valid) return;
        const Quat qz{0, 0, std::sin(guard_roll * 0.5f), std::cos(guard_roll * 0.5f)};
        const Quat qx{std::sin(guard_pitch * 0.5f), 0, 0, std::cos(guard_pitch * 0.5f)};
        const Quat qy{0, std::sin(guard_yaw * 0.5f), 0, std::cos(guard_yaw * 0.5f)};
        Mat4 desired = mat4_from_trs({0, 0, 0}, qy, {1, 1, 1}) *
                       mat4_from_trs({0, 0, 0}, qx, {1, 1, 1}) *
                       mat4_from_trs({0, 0, 0}, qz, {1, 1, 1}) *
                       mat4_from_trs({0, 0, 0}, {0, 1, 0, 0}, {1, 1, 1}) * guard_sheath_world;
        desired.m[12] = guard_x;
        desired.m[13] = guard_y;
        desired.m[14] = guard_z;
        shield_arm.offset = guard_forearm_inv * desired;
    };
    rebuild_guard_socket();
    auto rebuild_hand_socket = [&]() {
        if (!guard_socket_valid) return;
        const Quat qz{0, 0, std::sin(hand_roll * 0.5f), std::cos(hand_roll * 0.5f)};
        const Quat qx{std::sin(hand_pitch * 0.5f), 0, 0, std::cos(hand_pitch * 0.5f)};
        const Quat qy{0, std::sin(hand_yaw * 0.5f), 0, std::cos(hand_yaw * 0.5f)};
        Mat4 desired = mat4_from_trs({0, 0, 0}, qy, {1, 1, 1}) *
                       mat4_from_trs({0, 0, 0}, qx, {1, 1, 1}) *
                       mat4_from_trs({0, 0, 0}, qz, {1, 1, 1}) *
                       mat4_from_trs({0, 0, 0}, {0, 1, 0, 0}, {1, 1, 1}) * hand_sheath_world;
        desired.m[12] = hand_x;
        desired.m[13] = hand_y;
        desired.m[14] = hand_z;
        shield_hand.offset = hand_forearm_inv * desired;
    };
    rebuild_hand_socket();

    // --- sword: both placements authored in Blender. "Sword" carries the
    // sheathed socket; the invisible "SwordHandSocket" marker carries the
    // drawn-in-hand one, which we copy out and then collapse so it never
    // renders ---
    Model::Attachment sword_sheath{};
    Model::Attachment sword_hand{};
    bool sword_socket_valid = false;
    // the flute rides his hand, but only exists while he's playing it
    Model::Attachment flute_socket{};
    bool flute_valid = false;
    if (Model::Attachment* fl = app.link.find_attachment("Flute")) {
        flute_socket = *fl;
        flute_valid = true;
    }
    if (Model::Attachment* sw = app.link.find_attachment("Sword")) {
        sword_sheath = *sw;
        sword_hand = *sw;
        if (Model::Attachment* mk = app.link.find_attachment("SwordHandSocket")) {
            sword_hand.anchor_node = mk->anchor_node;
            sword_hand.offset = mk->offset;
            for (float& v : mk->offset.m) v = 0.0f;  // degenerate: invisible
            sword_socket_valid = true;
        }
    }
    if (shot_path) {
        if (const AnimClip* c = app.link.find_clip(shot_clip))
            app.clip_index = static_cast<int>(c - app.link.clips.data());
        app.clip_time = shot_time;
        if (shot_distance > 0) app.cam.distance = shot_distance;
        if (shot_yaw < 100.0f) app.cam.yaw = shot_yaw;
        app.viewer_mode = true;  // screenshots use the plain clip viewer
    }
    bool want_shot = false;
    app.player.init(app.link);

    const GLuint skin_prog = link_program(kSkinVS, kSkinFS);
    const GLuint grid_prog = link_program(kGridVS, kGridFS);
    if (!skin_prog || !grid_prog) return 1;
    const GLint u_viewproj = glGetUniformLocation(skin_prog, "uViewProj");
    const GLint u_model = glGetUniformLocation(skin_prog, "uModel");
    const GLint u_palette = glGetUniformLocation(skin_prog, "uPalette");
    const GLint u_tex = glGetUniformLocation(skin_prog, "uTex");
    const GLint u_sun = glGetUniformLocation(skin_prog, "uSunDir");
    const GLint g_viewproj = glGetUniformLocation(grid_prog, "uViewProj");

    // ground quad
    const float ground[] = {-20, 0, -20, 20, 0, -20, 20, 0, 20,
                            -20, 0, -20, 20, 0, 20, -20, 0, 20};
    GLuint grid_vao = 0, grid_vbo = 0;
    glGenVertexArrays(1, &grid_vao);
    glBindVertexArray(grid_vao);
    glGenBuffers(1, &grid_vbo);
    glBindBuffer(GL_ARRAY_BUFFER, grid_vbo);
    glBufferData(GL_ARRAY_BUFFER, sizeof(ground), ground, GL_STATIC_DRAW);
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 12, nullptr);
    glBindVertexArray(0);

    // target cube (per-face shade for readability)
    const GLuint cube_prog = link_program(kCubeVS, kCubeFS);
    const GLint c_viewproj = glGetUniformLocation(cube_prog, "uViewProj");
    std::vector<float> cube;
    {
        const float h = kTargetHalf;
        const Vec3 c = kTargetPos;
        const float faces[6][4] = {  // axis, sign, shade
            {0, 1, 0, 0.85f}, {0, -1, 0, 0.55f}, {1, 1, 0, 1.0f},
            {1, -1, 0, 0.4f}, {2, 1, 0, 0.7f}, {2, -1, 0, 0.7f}};
        for (const auto& f : faces) {
            const int axis = static_cast<int>(f[0]);
            const float sgn = f[1];
            const float shade = f[3];
            const int u = (axis + 1) % 3, v = (axis + 2) % 3;
            float base[3] = {c.x, c.y, c.z};
            base[axis] += sgn * h;
            const float du[2] = {-h, h};
            float quad[4][3];
            int corner = 0;
            for (const float su : du)
                for (const float sv : du) {
                    float p[3] = {base[0], base[1], base[2]};
                    p[u] += su;
                    p[v] += sv;
                    for (int k = 0; k < 3; ++k) quad[corner][k] = p[k];
                    ++corner;
                }
            const int tri[6] = {0, 1, 2, 2, 1, 3};
            for (const int idx : tri) {
                cube.insert(cube.end(), quad[idx], quad[idx] + 3);
                cube.push_back(shade);
            }
        }
    }
    GLuint cube_vao = 0, cube_vbo = 0;
    glGenVertexArrays(1, &cube_vao);
    glBindVertexArray(cube_vao);
    glGenBuffers(1, &cube_vbo);
    glBindBuffer(GL_ARRAY_BUFFER, cube_vbo);
    glBufferData(GL_ARRAY_BUFFER, static_cast<GLsizeiptr>(cube.size() * sizeof(float)),
                 cube.data(), GL_STATIC_DRAW);
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 16, nullptr);
    glEnableVertexAttribArray(1);
    glVertexAttribPointer(1, 1, GL_FLOAT, GL_FALSE, 16, reinterpret_cast<void*>(12));
    glBindVertexArray(0);

    // lock-on floor reticle: flat ring + four inward ticks, spun in-shader
    const GLuint reticle_prog = link_program(kReticleVS, kReticleFS);
    const GLint r_viewproj = glGetUniformLocation(reticle_prog, "uViewProj");
    const GLint r_center = glGetUniformLocation(reticle_prog, "uCenter");
    const GLint r_spin = glGetUniformLocation(reticle_prog, "uSpin");
    const GLint r_alpha = glGetUniformLocation(reticle_prog, "uAlpha");
    const GLint r_scale = glGetUniformLocation(reticle_prog, "uScale");
    std::vector<float> reticle;
    {
        // unit-radius geometry; sized per-target at draw time from its bounds
        const int segs = 48;
        const float r0 = 1.0f, r1 = 1.18f;
        for (int i = 0; i < segs; ++i) {
            const float a0 = 6.2831853f * i / segs;
            const float a1 = 6.2831853f * (i + 1) / segs;
            const float p[4][3] = {{r0 * std::cos(a0), 0, r0 * std::sin(a0)},
                                   {r1 * std::cos(a0), 0, r1 * std::sin(a0)},
                                   {r0 * std::cos(a1), 0, r0 * std::sin(a1)},
                                   {r1 * std::cos(a1), 0, r1 * std::sin(a1)}};
            const int tri[6] = {0, 1, 2, 2, 1, 3};
            for (const int idx : tri) reticle.insert(reticle.end(), p[idx], p[idx] + 3);
        }
        for (int t = 0; t < 4; ++t) {  // inward-pointing ticks
            const float a = 1.5707963f * t;
            const float ca = std::cos(a), sa = std::sin(a);
            const float tip = r0 - 0.29f, base = r0 - 0.04f, half = 0.11f;
            const float p[3][3] = {
                {tip * ca, 0, tip * sa},
                {base * ca - half * sa, 0, base * sa + half * ca},
                {base * ca + half * sa, 0, base * sa - half * ca}};
            for (const auto& v : p) reticle.insert(reticle.end(), v, v + 3);
        }
    }
    GLuint reticle_vao = 0, reticle_vbo = 0;
    glGenVertexArrays(1, &reticle_vao);
    glBindVertexArray(reticle_vao);
    glGenBuffers(1, &reticle_vbo);
    glBindBuffer(GL_ARRAY_BUFFER, reticle_vbo);
    glBufferData(GL_ARRAY_BUFFER, static_cast<GLsizeiptr>(reticle.size() * sizeof(float)),
                 reticle.data(), GL_STATIC_DRAW);
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 12, nullptr);
    glBindVertexArray(0);
    const GLsizei reticle_verts = static_cast<GLsizei>(reticle.size() / 3);

    // WW-style sky wind streaks: thin white corkscrew trails that draw in,
    // loop once or twice, and erase out, respawning around the player
    struct WindStreak {
        Vec3 origin{}, fwd{}, side{};
        float len = 4, amp = 0.4f, loops = 1, phase = 0, dur = 3, t = -1;
    };
    std::vector<WindStreak> winds(6);
    uint32_t wind_seed = 0x9d2c5680u ^ static_cast<uint32_t>(SDL_GetTicksNS());
    auto wrand = [&]() {
        wind_seed = wind_seed * 1664525u + 1013904223u;
        return static_cast<float>(wind_seed >> 8) * (1.0f / 16777216.0f);
    };
    auto wind_respawn = [&](WindStreak& w, bool stagger) {
        // world-anchored: streaks live in a fixed region of the map, not
        // around the player
        const float ang = wrand() * 6.2831853f;
        const float rad = wrand() * 30.0f;
        w.origin = {std::cos(ang) * rad, 0.9f + wrand() * 2.6f, std::sin(ang) * rad};
        // fixed world wind: everything blows toward -X ("left")
        w.fwd = {-1.0f, 0.0f, 0.0f};
        w.side = normalize(cross(w.fwd, Vec3{0, 1, 0}));
        w.len = 26.0f + wrand() * 14.0f;
        w.amp = 0.16f + wrand() * 0.14f;
        w.loops = 1.0f;
        w.phase = wrand() * 6.2831853f;
        w.dur = w.len / (3.2f + wrand() * 0.8f);  // steady travel speed
        w.t = -(stagger ? wrand() * 3.0f : 0.4f + wrand() * 1.8f);  // spawn delay
    };
    for (auto& w : winds) wind_respawn(w, true);
    auto wind_point = [](const WindStreak& w, float u) {
        const float phi = w.phase + w.loops * 6.2831853f * u;
        const float r = w.amp * std::sin(3.1415926f * u);
        return w.origin + w.fwd * (w.len * u) + w.side * (std::cos(phi) * r) +
               Vec3{0, std::sin(phi) * r, 0};
    };
    const GLuint wind_prog = link_program(kWindVS, kWindFS);
    const GLint w_viewproj = glGetUniformLocation(wind_prog, "uViewProj");
    GLuint wind_vao = 0, wind_vbo = 0;
    glGenVertexArrays(1, &wind_vao);
    glBindVertexArray(wind_vao);
    glGenBuffers(1, &wind_vbo);
    glBindBuffer(GL_ARRAY_BUFFER, wind_vbo);
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 16, nullptr);
    glEnableVertexAttribArray(1);
    glVertexAttribPointer(1, 1, GL_FLOAT, GL_FALSE, 16, reinterpret_cast<void*>(12));
    glBindVertexArray(0);
    std::vector<float> wind_verts;
    std::vector<int> wind_ranges;  // pairs: first vert, vert count

    // star sparkles sprinkling out of the flute while he plays
    struct Star {
        Vec3 pos{}, vel{};
        float life = 0, max_life = 1, size = 0.03f, spin = 0, spin_rate = 0;
    };
    std::vector<Star> stars;
    float star_timer = 0.0f;
    const GLuint star_prog = link_program(kStarVS, kStarFS);
    const GLint s_viewproj = glGetUniformLocation(star_prog, "uViewProj");
    GLuint star_vao = 0, star_vbo = 0;
    glGenVertexArrays(1, &star_vao);
    glBindVertexArray(star_vao);
    glGenBuffers(1, &star_vbo);
    glBindBuffer(GL_ARRAY_BUFFER, star_vbo);
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 24, nullptr);
    glEnableVertexAttribArray(1);
    glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, 24, reinterpret_cast<void*>(12));
    glEnableVertexAttribArray(2);
    glVertexAttribPointer(2, 1, GL_FLOAT, GL_FALSE, 24, reinterpret_cast<void*>(20));
    glBindVertexArray(0);
    std::vector<float> star_verts;

    // --- ocarina HUD ---
    const GLuint hud_prog = link_program(kHudVS, kHudFS);
    const GLint h_screen = glGetUniformLocation(hud_prog, "uScreen");
    GLuint hud_vao = 0, hud_vbo = 0;
    glGenVertexArrays(1, &hud_vao);
    glBindVertexArray(hud_vao);
    glGenBuffers(1, &hud_vbo);
    glBindBuffer(GL_ARRAY_BUFFER, hud_vbo);
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 24, nullptr);
    glEnableVertexAttribArray(1);
    glVertexAttribPointer(1, 4, GL_FLOAT, GL_FALSE, 24, reinterpret_cast<void*>(8));
    glBindVertexArray(0);
    std::vector<float> hud_verts;
    float hud_fade = 0.0f;

    // the clef glyph, expanded to RGBA so we only need core GL 1.1 formats
    const GLuint clef_prog = link_program(kHudTexVS, kHudTexFS);
    const GLint ct_screen = glGetUniformLocation(clef_prog, "uScreen");
    const GLint ct_color = glGetUniformLocation(clef_prog, "uColor");
    const GLint ct_tex = glGetUniformLocation(clef_prog, "uTex");
    GLuint clef_tex = 0;
    {
        std::vector<unsigned char> rgba(static_cast<size_t>(kClefW) * kClefH * 4);
        for (size_t i = 0; i < static_cast<size_t>(kClefW) * kClefH; ++i) {
            rgba[i * 4 + 0] = 255;
            rgba[i * 4 + 1] = 255;
            rgba[i * 4 + 2] = 255;
            rgba[i * 4 + 3] = kClefAlpha[i];
        }
        glGenTextures(1, &clef_tex);
        glBindTexture(GL_TEXTURE_2D, clef_tex);
        glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, kClefW, kClefH, 0, GL_RGBA,
                     GL_UNSIGNED_BYTE, rgba.data());
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
        glBindTexture(GL_TEXTURE_2D, 0);
    }
    GLuint clef_vao = 0, clef_vbo = 0;
    glGenVertexArrays(1, &clef_vao);
    glBindVertexArray(clef_vao);
    glGenBuffers(1, &clef_vbo);
    glBindBuffer(GL_ARRAY_BUFFER, clef_vbo);
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 16, nullptr);
    glEnableVertexAttribArray(1);
    glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, 16, reinterpret_cast<void*>(8));
    glBindVertexArray(0);

    // --- flute audio: one middle-C sample, pitched per semitone ---
    // a small pool of streams so overlapping notes ring together
    constexpr int kVoices = 6;
    SDL_AudioStream* voices[kVoices] = {};
    Uint8* flute_wav = nullptr;
    Uint32 flute_wav_len = 0;
    int voice_next = 0;
    {
        SDL_AudioSpec wav_spec{};
        std::string wpath = std::string(SDL_GetBasePath()) +
                            "..\\..\\assets\\panflute_c.wav";
        if (!SDL_LoadWAV(wpath.c_str(), &wav_spec, &flute_wav, &flute_wav_len))
            SDL_LoadWAV("assets/panflute_c.wav", &wav_spec, &flute_wav,
                        &flute_wav_len);
        if (flute_wav) {
            const SDL_AudioDeviceID dev =
                SDL_OpenAudioDevice(SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK, nullptr);
            if (dev) {
                for (SDL_AudioStream*& v : voices) {
                    v = SDL_CreateAudioStream(&wav_spec, nullptr);
                    if (!v) continue;
                    SDL_BindAudioStream(dev, v);
                }
                SDL_Log("flute audio: %u bytes, %d ch @ %d Hz", flute_wav_len,
                        wav_spec.channels, wav_spec.freq);
            } else {
                SDL_Log("no audio device: %s", SDL_GetError());
            }
        } else {
            SDL_Log("could not load assets/panflute_c.wav: %s", SDL_GetError());
        }
    }
    // semitones above middle C for keys 1..8 (C D E F G A B C')
    const int kScale[8] = {0, 2, 4, 5, 7, 9, 11, 12};
    // a pan flute plays one note at a time: starting a note releases whatever
    // was still ringing. Without this the 1.7s sample covers the gaps between
    // notes and the rhythm smears into a chord.
    float voice_gain[kVoices] = {};
    bool voice_releasing[kVoices] = {};
    auto play_note = [&](int semitones, float vel = 1.0f) {
        if (!flute_wav || !voices[0]) return;
        const int idx = voice_next;
        SDL_AudioStream* v = voices[idx];
        voice_next = (voice_next + 1) % kVoices;
        for (int i = 0; i < kVoices; ++i)
            if (i != idx && voices[i] && SDL_GetAudioStreamAvailable(voices[i]) > 0)
                voice_releasing[i] = true;
        SDL_ClearAudioStream(v);
        SDL_SetAudioStreamFrequencyRatio(
            v, std::pow(2.0f, static_cast<float>(semitones) / 12.0f));
        voice_gain[idx] = 0.85f * vel;
        voice_releasing[idx] = false;
        SDL_SetAudioStreamGain(v, voice_gain[idx]);
        SDL_PutAudioStreamData(v, flute_wav, static_cast<int>(flute_wav_len));
    };

    // notes played on the flute this session, packed as step*4 + (accidental+1)
    std::vector<int> flute_notes;
    bool was_fluting = false;
    char hud_message[64] = "";  // song names land here once one is recognised

    // --- songs: match what he plays, then perform the full arrangement ---
    // keys 6 2 4 6 2 4 -- A D F A D F, the Song of Time as OoT plays it
    // (C-right, A, C-down, twice over)
    const int kSongOfTime[6] = {5, 1, 3, 5, 1, 3};
    // Onsets taken straight from the Song of Time MIDI (120bpm, quarter=0.5s).
    // The D is the held note, not the A: "A  Daah  F". Note the two different
    // C's -- C5 up in the ACB run, but C4 down in the closing C E D.
    struct SongNote { float t; int step; float vel; };
    const SongNote kSongOfTimeFull[17] = {
        {0.00f, 5, 1.0f},   // A4  quarter
        {0.50f, 1, 1.0f},   // D4  half
        {1.50f, 3, 1.0f},   // F4  quarter
        {2.00f, 5, 1.0f},   // A4  quarter
        {2.50f, 1, 1.0f},   // D4  half
        {3.50f, 3, 1.0f},   // F4  quarter
        {4.00f, 5, 1.0f},   // A4  eighth
        {4.25f, 7, 1.0f},   // C5  eighth
        {4.50f, 6, 1.0f},   // B4  quarter
        {5.00f, 4, 1.0f},   // G4  quarter
        {5.50f, 3, 1.0f},   // F4  eighth
        {5.75f, 4, 1.0f},   // G4  eighth
        {6.00f, 5, 1.0f},   // A4  quarter
        {6.50f, 1, 1.0f},   // D4  quarter
        {7.00f, 0, 1.0f},   // C4  eighth  (the low C, key 1)
        {7.25f, 2, 1.0f},   // E4  eighth
        {7.50f, 1, 1.0f},   // D4  dotted half
    };

    // --- Song of Skies: ours, not Nintendo's. Built like Zelda's Lullaby --
    // a lyrical 3/4 hymn whose opening phrase IS the motif you play, so the
    // trigger feels like the song. The shape is an arc: C rises through the
    // fifth to the octave, then falls home, which is the "sky" idea.
    // keys 1 5 8 6 5 3  (C G C' A G E)
    const int kSongOfSkies[6] = {0, 4, 7, 5, 4, 2};
    // 120bpm, quarter 0.5s. Flowing rather than stately: no long holds, and
    // eighth-note pairs on the turns give it lift instead of a plod. Four
    // bars of 4/4, resolving on the held C.
    // Plays through to the D, hangs there, then takes it from the top; the
    // second time round the D resolves onto the C and it's done.
    const SongNote kSongOfSkiesFull[31] = {
        // -- first pass, ending on the D -----------------------------------
        { 0.00f, 0, 1.0f},   //  1  C   quarter
        { 0.50f, 4, 0.9f},   //  2  G   quarter
        { 1.00f, 7, 1.0f},   //  3  C'  quarter
        { 1.50f, 5, 0.9f},   //  4  A   eighth
        { 1.75f, 4, 0.9f},   //  5  G   eighth
        { 2.00f, 2, 0.9f},   //  6  E   quarter
        { 2.50f, 4, 1.0f},   //  7  G   half     -- breath
        { 3.50f, 2, 0.9f},   //  8  E   eighth
        { 3.75f, 4, 0.9f},   //  9  G   eighth
        { 4.00f, 7, 1.0f},   // 10  C'  quarter
        { 4.50f, 6, 1.0f},   // 11  B   quarter
        { 5.00f, 5, 0.9f},   // 12  A   eighth
        { 5.25f, 4, 0.9f},   // 13  G   eighth
        { 5.50f, 2, 0.9f},   // 14  E   quarter
        { 6.00f, 1, 0.9f},   // 15  D   half     -- hangs, then back to the top
        // -- second pass ---------------------------------------------------
        { 7.00f, 0, 1.0f},   //  1  C   quarter
        { 7.50f, 4, 0.9f},   //  2  G   quarter
        { 8.00f, 7, 1.0f},   //  3  C'  quarter
        { 8.50f, 5, 0.9f},   //  4  A   eighth
        { 8.75f, 4, 0.9f},   //  5  G   eighth
        { 9.00f, 2, 0.9f},   //  6  E   quarter
        { 9.50f, 4, 1.0f},   //  7  G   half     -- breath
        {10.50f, 2, 0.9f},   //  8  E   eighth
        {10.75f, 4, 0.9f},   //  9  G   eighth
        {11.00f, 7, 1.0f},   // 10  C'  quarter
        {11.50f, 6, 1.0f},   // 11  B   quarter
        {12.00f, 5, 0.9f},   // 12  A   eighth
        {12.25f, 4, 0.9f},   // 13  G   eighth
        {12.50f, 2, 0.9f},   // 14  E   quarter
        {13.00f, 1, 0.9f},   // 15  D   quarter  -- this time it resolves
        {13.50f, 0, 1.0f},   // 16  C   held     -- home
    };

    struct Song {
        const char* title;
        const int* motif;
        size_t motif_len;
        const SongNote* full;
        size_t full_len;
    };
    // lengths derived from the arrays: hand-written counts drift when a
    // melody is edited and the tune silently stops early
    const Song kSongs[2] = {
        {"YOU PLAYED SONG OF TIME!", kSongOfTime, std::size(kSongOfTime),
         kSongOfTimeFull, std::size(kSongOfTimeFull)},
        {"YOU PLAYED SONG OF SKIES!", kSongOfSkies, std::size(kSongOfSkies),
         kSongOfSkiesFull, std::size(kSongOfSkiesFull)},
    };

    const Song* song_active = nullptr;
    bool song_playing = false;
    float song_timer = 0.0f;
    size_t song_index = 0;

    // last frame's view-projection: lets the sim test whether the lock-on
    // target is actually on screen before allowing a lock
    Mat4 last_viewproj{};
    bool have_viewproj = false;

    Uint64 prev_ns = SDL_GetTicksNS();
    double accumulator = 0.0;
    Uint64 fps_frames = 0;
    Uint64 fps_last_ns = prev_ns;
    set_title(app, 0);

    while (app.running) {
        SDL_Event ev;
        while (SDL_PollEvent(&ev)) {
            switch (ev.type) {
                case SDL_EVENT_QUIT:
                    app.running = false;
                    break;
                case SDL_EVENT_KEY_DOWN:
                    if (ev.key.key == SDLK_ESCAPE) app.running = false;
                    if (ev.key.key == SDLK_F2) want_shot = true;
                    if (ev.key.key == SDLK_F5 || ev.key.key == SDLK_F6 ||
                        ev.key.key == SDLK_F7 || ev.key.key == SDLK_F8) {
                        // live camera-arc tuning
                        if (ev.key.key == SDLK_F5) cam_rot_cap -= 0.01f;
                        if (ev.key.key == SDLK_F6) cam_rot_cap += 0.01f;
                        if (ev.key.key == SDLK_F7) cam_zoom_max -= 0.2f;
                        if (ev.key.key == SDLK_F8) cam_zoom_max += 0.2f;
                        if (cam_rot_cap < -0.3f) cam_rot_cap = -0.3f;
                        if (cam_rot_cap > 0.3f) cam_rot_cap = 0.3f;
                        if (cam_zoom_max < 0.4f) cam_zoom_max = 0.4f;
                        if (cam_zoom_max > 6.0f) cam_zoom_max = 6.0f;
                        char buf[128];
                        SDL_snprintf(buf, sizeof(buf),
                                     "camera arc: rot cap=%.2f zoom max=%.1f",
                                     cam_rot_cap, cam_zoom_max);
                        SDL_SetWindowTitle(app.window, buf);
                        SDL_Log("%s", buf);
                        save_cam_tune();
                    }
                    if (ev.key.key == SDLK_F1 && !ev.key.repeat) {
                        app.viewer_mode = !app.viewer_mode;
                        set_title(app, 0);
                    }
                    if (!ev.key.repeat && !app.viewer_mode) {
                        const bool* ks = SDL_GetKeyboardState(nullptr);
                        const bool guarding_now =
                            ks[SDL_SCANCODE_LSHIFT] || ks[SDL_SCANCODE_RSHIFT];
                        // while guarding, J belongs to the tuning keys below
                        if (ev.key.key == SDLK_J && !guarding_now) app.key_attack = true;
                        if (ev.key.key == SDLK_I && !guarding_now) app.key_flute = true;
                        // 1..8 walk the octave; hold up/down for the sharp or
                        // flat, so the whole chromatic 12 is reachable
                        if (app.player.state == PlayerState::Flute && !song_playing) {
                            const SDL_Keycode nk[8] = {SDLK_1, SDLK_2, SDLK_3,
                                                       SDLK_4, SDLK_5, SDLK_6,
                                                       SDLK_7, SDLK_8};
                            for (int n = 0; n < 8; ++n) {
                                if (ev.key.key != nk[n]) continue;
                                const bool* ks2 = SDL_GetKeyboardState(nullptr);
                                int acc = 0;
                                if (ks2[SDL_SCANCODE_UP]) acc = 1;
                                else if (ks2[SDL_SCANCODE_DOWN]) acc = -1;
                                if (flute_notes.size() >= 8) flute_notes.clear();
                                flute_notes.push_back(n * 4 + (acc + 1));
                                play_note(kScale[n] + acc);

                                // did the last few notes spell any song?
                                for (const Song& song : kSongs) {
                                    if (flute_notes.size() < song.motif_len) continue;
                                    bool hit = true;
                                    const size_t off =
                                        flute_notes.size() - song.motif_len;
                                    for (size_t k = 0; k < song.motif_len && hit; ++k) {
                                        const int v = flute_notes[off + k];
                                        hit = (v / 4 == song.motif[k]) && (v % 4 == 1);
                                    }
                                    if (!hit) continue;
                                    // clear the staff, name it, play it in full
                                    flute_notes.clear();
                                    SDL_strlcpy(hud_message, song.title,
                                                sizeof(hud_message));
                                    song_active = &song;
                                    song_playing = true;
                                    song_timer = -0.6f;   // a beat of silence
                                    song_index = 0;
                                    break;
                                }
                            }
                        }
                        if (ev.key.key == SDLK_SPACE) {
                            // standing still with the gear out: play it away
                            // (rolling needs movement input anyway)
                            if (app.player.state == PlayerState::Locomotion &&
                                app.player.speed < 0.05f && shield_in_hand)
                                app.key_sheathe = true;
                            else
                                app.key_roll = true;
                        }
                    }
                    if (app.viewer_mode && !app.link.clips.empty()) {
                        const int n = static_cast<int>(app.link.clips.size());
                        if (ev.key.key == SDLK_RIGHT) {
                            app.clip_index = (app.clip_index + 1) % n;
                            app.clip_time = 0.0;
                            set_title(app, 0);
                        } else if (ev.key.key == SDLK_LEFT) {
                            app.clip_index = (app.clip_index + n - 1) % n;
                            app.clip_time = 0.0;
                            set_title(app, 0);
                        }
                    }
                    {
                        // shield placement tuning (repeat-friendly): Guard clip
                        // in the viewer / guard held in game tunes the guard
                        // socket; other viewer clips tune the relaxed in-hand
                        // socket
                        const bool* ks = SDL_GetKeyboardState(nullptr);
                        const bool guard_held =
                            ks[SDL_SCANCODE_LSHIFT] || ks[SDL_SCANCODE_RSHIFT];
                        if (!app.viewer_mode && !guard_held) break;
                        const bool tune_guard =
                            app.viewer_mode
                                ? (!app.link.clips.empty() &&
                                   app.link.clips[app.clip_index].name == "Guard")
                                : true;
                        float& tx = tune_guard ? guard_x : hand_x;
                        float& ty = tune_guard ? guard_y : hand_y;
                        float& tz = tune_guard ? guard_z : hand_z;
                        float& troll = tune_guard ? guard_roll : hand_roll;
                        float& tpitch = tune_guard ? guard_pitch : hand_pitch;
                        float& tyaw = tune_guard ? guard_yaw : hand_yaw;
                        const float st = 0.01f;
                        bool tuned = true;
                        switch (ev.key.key) {
                            case SDLK_I: ty += st; break;
                            case SDLK_K: ty -= st; break;
                            case SDLK_J: tx += st; break;
                            case SDLK_L: tx -= st; break;
                            case SDLK_U: tz -= st; break;
                            case SDLK_O: tz += st; break;
                            case SDLK_LEFTBRACKET: troll -= 2.0f * st; break;
                            case SDLK_RIGHTBRACKET: troll += 2.0f * st; break;
                            case SDLK_COMMA: tpitch -= 2.0f * st; break;
                            case SDLK_PERIOD: tpitch += 2.0f * st; break;
                            case SDLK_N: tyaw -= 2.0f * st; break;
                            case SDLK_M: tyaw += 2.0f * st; break;
                            default: tuned = false; break;
                        }
                        if (tuned) {
                            if (tune_guard) { rebuild_guard_socket(); save_guard_tune(); }
                            else           { rebuild_hand_socket(); save_hand_tune(); }
                            char buf[192];
                            SDL_snprintf(buf, sizeof(buf),
                                         "%s shield: x=%.3f y=%.3f z=%.3f roll=%.3f pitch=%.3f yaw=%.3f",
                                         tune_guard ? "guard" : "hand", tx, ty, tz,
                                         troll, tpitch, tyaw);
                            SDL_SetWindowTitle(app.window, buf);
                            SDL_Log("%s", buf);
                        }
                    }
                    break;
                case SDL_EVENT_GAMEPAD_ADDED:
                    if (!app.pad) app.pad = SDL_OpenGamepad(ev.gdevice.which);
                    break;
                case SDL_EVENT_GAMEPAD_REMOVED:
                    if (app.pad) { SDL_CloseGamepad(app.pad); app.pad = nullptr; }
                    break;
                case SDL_EVENT_GAMEPAD_BUTTON_DOWN:
                    if (!app.viewer_mode) {
                        if (ev.gbutton.button == SDL_GAMEPAD_BUTTON_SOUTH) app.key_roll = true;
                        if (ev.gbutton.button == SDL_GAMEPAD_BUTTON_WEST) app.key_attack = true;
                    }
                    break;
                case SDL_EVENT_MOUSE_BUTTON_DOWN:
                    // viewer mode keeps mouse orbit; in game the camera is
                    // arrow-key driven only
                    if (ev.button.button == SDL_BUTTON_RIGHT && app.viewer_mode)
                        app.dragging = true;
                    if (ev.button.button == SDL_BUTTON_LEFT && !app.viewer_mode)
                        app.key_attack = true;
                    break;
                case SDL_EVENT_MOUSE_BUTTON_UP:
                    if (ev.button.button == SDL_BUTTON_RIGHT) app.dragging = false;
                    break;
                case SDL_EVENT_MOUSE_MOTION:
                    if (app.dragging) {
                        app.cam.yaw -= ev.motion.xrel * 0.008f;
                        app.cam.pitch += ev.motion.yrel * 0.006f;
                        if (app.cam.pitch > 1.4f) app.cam.pitch = 1.4f;
                        if (app.cam.pitch < -0.2f) app.cam.pitch = -0.2f;
                    }
                    break;
                case SDL_EVENT_MOUSE_WHEEL:
                    app.cam.distance -= ev.wheel.y * 0.3f;
                    if (app.cam.distance < 1.2f) app.cam.distance = 1.2f;
                    if (app.cam.distance > 12.0f) app.cam.distance = 12.0f;
                    break;
                default:
                    break;
            }
        }

        const Uint64 now_ns = SDL_GetTicksNS();
        double frame_dt = static_cast<double>(now_ns - prev_ns) / 1e9;
        prev_ns = now_ns;
        if (frame_dt > 0.25) frame_dt = 0.25;

        // fade out notes that have been released, so each one ends cleanly
        for (int i = 0; i < kVoices; ++i) {
            if (!voices[i] || !voice_releasing[i]) continue;
            voice_gain[i] -= static_cast<float>(frame_dt) * (0.85f / 0.16f);
            if (voice_gain[i] <= 0.0f) {
                voice_gain[i] = 0.0f;
                voice_releasing[i] = false;
                SDL_ClearAudioStream(voices[i]);
            } else {
                SDL_SetAudioStreamGain(voices[i], voice_gain[i]);
            }
        }

        accumulator += frame_dt;
        while (accumulator >= kFixedDt) {
            app.sim_time += kFixedDt;
            app.clip_time += kFixedDt;
            if (!app.viewer_mode) {
                // gather input: keyboard + gamepad, camera-relative
                const bool* keys = SDL_GetKeyboardState(nullptr);
                float in_x = 0, in_y = 0;  // stick space: y = forward
                if (keys[SDL_SCANCODE_W]) in_y += 1;
                if (keys[SDL_SCANCODE_S]) in_y -= 1;
                if (keys[SDL_SCANCODE_D]) in_x += 1;
                if (keys[SDL_SCANCODE_A]) in_x -= 1;
                bool guard = keys[SDL_SCANCODE_LSHIFT] || keys[SDL_SCANCODE_RSHIFT];
                if (app.pad) {
                    in_x += SDL_GetGamepadAxis(app.pad, SDL_GAMEPAD_AXIS_LEFTX) / 32767.0f;
                    in_y -= SDL_GetGamepadAxis(app.pad, SDL_GAMEPAD_AXIS_LEFTY) / 32767.0f;
                    guard = guard ||
                            SDL_GetGamepadButton(app.pad, SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER);
                }
                const float mag = std::sqrt(in_x * in_x + in_y * in_y);
                if (mag > 1.0f) { in_x /= mag; in_y /= mag; }
                // camera basis on the ground plane
                const Vec3 eye = app.cam.eye();
                Vec3 fwd = app.cam.target - eye;
                fwd.y = 0;
                fwd = normalize(fwd);
                const Vec3 right{-fwd.z, 0, fwd.x};

                Player::Input in;
                in.move_x = fwd.x * in_y + right.x * in_x;
                in.move_z = fwd.z * in_y + right.z * in_x;
                in.attack_pressed = app.key_attack;
                in.roll_pressed = app.key_roll;
                in.flute_pressed = app.key_flute;
                in.sheathe_pressed = app.key_sheathe;
                in.guard_held = guard;
                in.cam_yaw = app.cam.yaw;  // he turns to face the lens
                // you can only lock on to what's on screen: project the target
                // through last frame's camera. a wider margin while already
                // locked keeps it from flickering off at the screen edge
                bool target_visible = false;
                if (have_viewproj) {
                    const Vec3 tp = kTargetPos + Vec3{0, 0.5f, 0};
                    const float* m = last_viewproj.m;
                    const float cx = m[0] * tp.x + m[4] * tp.y + m[8] * tp.z + m[12];
                    const float cy = m[1] * tp.x + m[5] * tp.y + m[9] * tp.z + m[13];
                    const float cw = m[3] * tp.x + m[7] * tp.y + m[11] * tp.z + m[15];
                    const float margin = app.player.locked ? 1.35f : 1.0f;
                    target_visible = cw > 0.0f && std::fabs(cx) <= margin * cw &&
                                     std::fabs(cy) <= margin * cw;
                }
                in.has_target = target_visible;
                in.target_pos = kTargetPos;
                app.player.weapons_drawn = shield_in_hand;
                app.key_attack = app.key_roll = app.key_flute = false;
                app.key_sheathe = false;
                app.player.update(in, static_cast<float>(kFixedDt));
                if (app.player.wants_draw) {  // the attack unsheathed everything
                    app.player.wants_draw = false;
                    shield_in_hand = true;
                }
            }
            accumulator -= kFixedDt;
        }

        // blowing the flute swaps in the eye.5 (closed-eye) face texture
        const bool blowing =
            app.viewer_mode
                ? (!app.link.clips.empty() && app.link.clips[app.clip_index].name == "Flute")
                : (app.player.anim.clip && app.player.anim.clip->name == "Flute");

        // sheathing: sword and shield both ride the hand until his hand
        // reaches the scabbard, halfway through, then they sit on his back
        if (!app.viewer_mode && app.player.state == PlayerState::Sheathe &&
            app.player.anim.clip && app.player.anim.clip == app.player.clips.sheathe) {
            const float end = app.player.anim.clip_end();
            if (end > 0.0f && app.player.anim.time >= end * 0.5f)
                shield_in_hand = false;
        }

        // during the first part of SlashDraw the gear is still on his back --
        // it comes out as the hand reaches the hilt
        bool mid_draw = false;
        if (!app.viewer_mode && app.player.anim.clip &&
            app.player.anim.clip == app.player.clips.slash_draw) {
            const float end = app.player.anim.clip_end();
            mid_draw = end > 0.0f && app.player.anim.time < end * 0.35f;
        }

        // shield rides the forearm while guarding; once it's been raised it
        // stays in hand (relaxed socket) through idle/run instead of returning
        // to the back. viewer: Guard clip = guard socket, other clips = hand
        if (Model::Attachment* sh = app.link.find_attachment("Shield")) {
            if (!app.viewer_mode && app.player.anim.overlay != nullptr)
                shield_in_hand = true;
            const bool guard_socket =
                app.viewer_mode
                    ? (!app.link.clips.empty() &&
                       app.link.clips[app.clip_index].name == "Guard")
                    : (app.player.anim.overlay != nullptr);
            const bool hand_socket = !guard_socket && !mid_draw && !blowing &&
                                     (app.viewer_mode || shield_in_hand);
            if (guard_socket && shield_arm.slot >= 0)
                *sh = shield_arm;
            else if (hand_socket && shield_hand.slot >= 0)
                *sh = shield_hand;
            else
                *sh = shield_sheath;
        }
        if (flute_valid) {
            if (Model::Attachment* fl = app.link.find_attachment("Flute")) {
                *fl = flute_socket;
                if (!blowing)
                    for (float& v : fl->offset.m) v = 0.0f;  // collapsed = hidden
            }
        }
        // sword: drawn once weapons are out (same state as the shield); the
        // viewer draws it for the attack clips so both sockets are visible
        if (sword_socket_valid) {
            if (Model::Attachment* sw = app.link.find_attachment("Sword")) {
                bool drawn = shield_in_hand && !mid_draw && !blowing;
                if (app.viewer_mode) {
                    const std::string cn = app.link.clips.empty()
                                               ? std::string()
                                               : app.link.clips[app.clip_index].name;
                    drawn = cn == "Slash" || cn == "Slash2" || cn == "SlashDraw";
                }
                *sw = drawn ? sword_hand : sword_sheath;
            }
        }

        // animate
        if (app.viewer_mode) {
            if (!app.link.clips.empty()) {
                const AnimClip& clip = app.link.clips[app.clip_index];
                float t = 0.0f;
                if (clip.duration > 0.0f)
                    t = static_cast<float>(std::fmod(app.clip_time, clip.duration));
                app.link.evaluate(clip, t);
            }
        } else {
            app.player.anim.apply(app.link);
            // camera: free mode tracks Link exactly (no lag); the lock-on
            // framing fades in/out via lock_blend so toggling never snaps
            const Vec3 head = app.player.pos + Vec3{0, 0.85f, 0};
            const float k = std::min(1.0f, 3.5f * static_cast<float>(frame_dt));
            app.lock_blend += ((app.player.locked ? 1.0f : 0.0f) - app.lock_blend) * k;
            if (app.player.locked && !app.was_locked) {
                app.free_yaw = app.cam.yaw;  // remember the pre-lock angle
                app.free_pitch = app.cam.pitch;
                app.lock_cam_manual = false;
                // nudge toward whichever side the camera already hangs on, so
                // locking on swings the shorter way and frames that flank
                Vec3 away0 = app.player.pos - kTargetPos;
                away0.y = 0;
                float side_dy = app.cam.yaw - std::atan2(away0.x, away0.z);
                while (side_dy > 3.14159265f) side_dy -= 6.2831853f;
                while (side_dy < -3.14159265f) side_dy += 6.2831853f;
                // start on whichever side the camera already hangs
                app.lock_offset = side_dy >= 0.0f ? kLockMaxOffset : -kLockMaxOffset;
            }
            app.was_locked = app.player.locked;
            if (app.player.locked && app.dragging) app.lock_cam_manual = true;
            if (!app.player.locked && app.lock_blend > 0.01f) {
                // any camera input after unlocking hands control back at once
                // instead of fighting the ease-back until the blend decays
                const bool* ks = SDL_GetKeyboardState(nullptr);
                if (app.dragging || ks[SDL_SCANCODE_LEFT] || ks[SDL_SCANCODE_RIGHT] ||
                    ks[SDL_SCANCODE_UP] || ks[SDL_SCANCODE_DOWN]) {
                    // stop steering, but bleed the framing out over ~0.1s so
                    // the look-at point doesn't snap
                    app.lock_blend *=
                        std::max(0.0f, 1.0f - 10.0f * static_cast<float>(frame_dt));
                } else {
                    // ease back to where the camera was before locking on
                    float dy = app.free_yaw - app.cam.yaw;
                    while (dy > 3.14159265f) dy -= 6.2831853f;
                    while (dy < -3.14159265f) dy += 6.2831853f;
                    app.cam.yaw += dy * k;
                    app.cam.pitch += (app.free_pitch - app.cam.pitch) * k;
                }
            }
            // arrow keys: free camera orbits; while locked they're a hard
            // switch between the left and right framing side -- never resting
            // in between (the camera's own ease supplies the swing)
            {
                const bool* ks = SDL_GetKeyboardState(nullptr);
                const float orbit = (ks[SDL_SCANCODE_LEFT] ? 1.0f : 0.0f) -
                                    (ks[SDL_SCANCODE_RIGHT] ? 1.0f : 0.0f);
                if (orbit != 0.0f && app.player.locked)
                    app.lock_offset = orbit > 0.0f ? -kLockMaxOffset : kLockMaxOffset;
                if (!app.player.locked) {
                    // eased orbit: ramps up while held, coasts to a stop on
                    // release instead of cutting dead
                    const float dt_o = static_cast<float>(frame_dt);
                    const float k_o = std::min(1.0f, (orbit != 0.0f ? 16.0f : 9.0f) * dt_o);
                    app.orbit_vel += (orbit * 2.2f - app.orbit_vel) * k_o;
                    app.cam.yaw += app.orbit_vel * dt_o;
                } else {
                    app.orbit_vel = 0.0f;
                }
                // up/down (free camera): pull-back is the star -- distance
                // grows, with only a whisper of upward rotation
                const float tilt = (ks[SDL_SCANCODE_DOWN] ? 1.0f : 0.0f) -
                                   (ks[SDL_SCANCODE_UP] ? 1.0f : 0.0f);
                const bool fluting = app.player.state == PlayerState::Flute;
                if (fluting) {
                    // ocarina framing: ease down into the low, close shot
                    // (the same pose the up arrow reaches)
                    app.cam_arc += (-1.0f - app.cam_arc) *
                                   std::min(1.0f, 3.0f * static_cast<float>(frame_dt));
                }
                if (tilt != 0.0f || fluting) {  // vertical arc works locked or free
                    // one clean sweep: a single arc value slides ground-level
                    // angle (-1) .. default (0) .. pulled-out overview (+1),
                    // and pitch + pull are both derived from it, eased in step
                    const float dt_f = static_cast<float>(frame_dt);
                    if (!fluting) {
                        app.cam_arc += tilt * 2.6f * dt_f;
                        if (app.cam_arc > 1.0f) app.cam_arc = 1.0f;
                        if (app.cam_arc < -1.0f) app.cam_arc = -1.0f;
                    }
                    const float def = OrbitCamera::kDefaultPitch;
                    // zoom rides the whole arc: out toward the top, IN toward
                    // the low ground-level shot -- never a dead zone. spans
                    // sized so the arc ends land at the same absolute
                    // distances as before the default was pushed out
                    // the WHOLE sweep is one smooth curve: the eye rides a
                    // quadratic bezier through three poses -- low close-up
                    // (-1), default (0), far pulled-out (+1) -- in the
                    // vertical plane. no segments, no mode changes; rotation
                    // and zoom blend across the entire trip. knobs: F5-F8
                    // rotation travels the ENTIRE sweep: strictly linear from
                    // the low bottom angle to the top angle, one direction
                    // only. distance runs close -> default -> far through a
                    // smooth curve. pitch can never double back.
                    const float u = (app.cam_arc + 1.0f) * 0.5f;
                    const float d0 = app.cam.distance;
                    const float dists[3] = {d0 - 2.1f, d0, d0 + cam_zoom_max};
                    const float dctrl = 2.0f * dists[1] - 0.5f * (dists[0] + dists[2]);
                    const float want_pull = (1 - u) * (1 - u) * dists[0] +
                                            2.0f * u * (1 - u) * dctrl +
                                            u * u * dists[2] - d0;
                    const float want_pitch =
                        0.08f + u * (def + cam_rot_cap - 0.08f);
                    const float e = std::min(1.0f, 12.0f * dt_f);
                    app.cam.pull += (want_pull - app.cam.pull) * e;
                    app.cam.pitch += (want_pitch - app.cam.pitch) * e;
                }
            }
            if (app.player.locked && !app.lock_cam_manual) {
                Vec3 away = app.player.pos - kTargetPos;
                away.y = 0;
                const float base_yaw = std::atan2(away.x, away.z);
                // behind Link, nudged off-axis so he sits off-center (cinematic)
                const float want_yaw = base_yaw + app.lock_offset;
                float dy = want_yaw - app.cam.yaw;
                while (dy > 3.14159265f) dy -= 6.2831853f;
                while (dy < -3.14159265f) dy += 6.2831853f;
                const float kf = std::min(1.0f, 8.0f * static_cast<float>(frame_dt));
                app.cam.yaw += dy * kf;
                // pitch stays owned by the vertical arc (works while locked)
            }
            // bias toward the cube by a CAPPED offset so backing away from it
            // doesn't slide Link toward the lens (fake zoom)
            Vec3 to_cube = (kTargetPos + Vec3{0, 0.5f, 0}) - head;
            const float cube_dist = std::sqrt(dot(to_cube, to_cube));
            const float bias = std::min(0.6f, cube_dist * 0.15f);
            const Vec3 lock_target =
                cube_dist > 1e-4f ? head + to_cube * (bias / cube_dist) : head;
            // pulling out lifts the aim slightly toward the horizon so the
            // view reads as backing away, not staring down at the floor
            Vec3 free_target = head;
            free_target.y += app.cam.pull * 0.10f;
            app.cam.target = lerp(free_target, lock_target, app.lock_blend);
        }

        // render
        int fb_w = 0, fb_h = 0;
        SDL_GetWindowSizeInPixels(app.window, &fb_w, &fb_h);
        glViewport(0, 0, fb_w, fb_h);
        glClearColor(0.35f, 0.58f, 0.71f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
        glEnable(GL_DEPTH_TEST);

        const float aspect = fb_h > 0 ? static_cast<float>(fb_w) / fb_h : 1.0f;
        const Mat4 proj = mat4_perspective(50.0f * 3.14159265f / 180.0f, aspect, 0.05f, 100.0f);
        const Mat4 view = mat4_look_at(app.cam.eye(), app.cam.target, {0, 1, 0});
        // (viewproj is stored below for next frame's on-screen target test)
        const Mat4 viewproj = proj * view;
        last_viewproj = viewproj;
        have_viewproj = true;

        glUseProgram(grid_prog);
        glUniformMatrix4fv(g_viewproj, 1, GL_FALSE, viewproj.m);
        glBindVertexArray(grid_vao);
        glDrawArrays(GL_TRIANGLES, 0, 6);

        glUseProgram(cube_prog);
        glUniformMatrix4fv(c_viewproj, 1, GL_FALSE, viewproj.m);
        glBindVertexArray(cube_vao);
        glDrawArrays(GL_TRIANGLES, 0, 36);

        // floor reticle under the target, fading with lock engagement
        if (!app.viewer_mode && app.lock_blend > 0.01f) {
            glEnable(GL_BLEND);
            glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
            glDepthMask(GL_FALSE);
            glUseProgram(reticle_prog);
            glUniformMatrix4fv(r_viewproj, 1, GL_FALSE, viewproj.m);
            const float center[3] = {kTargetPos.x, 0.02f, kTargetPos.z};
            glUniform3fv(r_center, 1, center);
            // ring hugs the target: ground-diagonal bounding radius + margin
            glUniform1f(r_scale, kTargetHalf * 1.41421f * 1.12f);
            glUniform1f(r_spin, static_cast<float>(app.sim_time) * 1.2f);
            glUniform1f(r_alpha, 0.85f * app.lock_blend);
            glBindVertexArray(reticle_vao);
            glDrawArrays(GL_TRIANGLES, 0, reticle_verts);
            glDepthMask(GL_TRUE);
            glDisable(GL_BLEND);
        }

        // sky wind streaks (game mode): a moving window along each corkscrew
        // path, ribbon-billboarded toward the camera
        if (!app.viewer_mode) {
            wind_verts.clear();
            wind_ranges.clear();
            const Vec3 wc_eye = app.cam.eye();
            const Vec3 vdir = normalize(app.cam.target - wc_eye);
            constexpr float kTail = 0.28f;
            constexpr int kSegs = 22;
            for (auto& w : winds) {
                w.t += static_cast<float>(frame_dt);
                const float span = w.dur;
                if (w.t > span) wind_respawn(w, false);
                if (w.t < 0.0f) continue;
                const float h = (w.t / span) * (1.0f + kTail);
                const float u1 = std::min(h, 1.0f);
                const float u0 = std::max(h - kTail, 0.0f);
                if (u1 - u0 < 0.02f) continue;
                const int first = static_cast<int>(wind_verts.size() / 4);
                for (int i = 0; i < kSegs; ++i) {
                    const float f = static_cast<float>(i) / (kSegs - 1);
                    const float u = u0 + (u1 - u0) * f;
                    const Vec3 p = wind_point(w, u);
                    const Vec3 tan = wind_point(w, u + 0.01f) - p;
                    Vec3 sidev = cross(tan, vdir);
                    const float sl = std::sqrt(dot(sidev, sidev));
                    if (sl > 1e-5f) sidev = sidev * (1.0f / sl);
                    const float taper = std::sin(3.1415926f * f);
                    const float half_w = 0.035f * (0.35f + 0.65f * taper);
                    const float alpha = 0.55f * taper;
                    for (const float s : {1.0f, -1.0f}) {
                        const Vec3 v = p + sidev * (half_w * s);
                        wind_verts.insert(wind_verts.end(), {v.x, v.y, v.z, alpha});
                    }
                }
                wind_ranges.push_back(first);
                wind_ranges.push_back(kSegs * 2);
            }
            if (!wind_ranges.empty()) {
                glEnable(GL_BLEND);
                glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
                glDepthMask(GL_FALSE);
                glUseProgram(wind_prog);
                glUniformMatrix4fv(w_viewproj, 1, GL_FALSE, viewproj.m);
                glBindVertexArray(wind_vao);
                glBindBuffer(GL_ARRAY_BUFFER, wind_vbo);
                glBufferData(GL_ARRAY_BUFFER,
                             static_cast<GLsizeiptr>(wind_verts.size() * sizeof(float)),
                             wind_verts.data(), GL_STREAM_DRAW);
                for (size_t i = 0; i + 1 < wind_ranges.size(); i += 2)
                    glDrawArrays(GL_TRIANGLE_STRIP, wind_ranges[i], wind_ranges[i + 1]);
                glDepthMask(GL_TRUE);
                glDisable(GL_BLEND);
            }
        }

        // --- star sparkles falling out of the flute ---
        {
            const float dt_s = static_cast<float>(frame_dt);
            if (blowing && flute_valid) {
                // emit at the flute itself: its palette slot already holds
                // world(hand) * placement for this frame
                const Mat4& pal = app.link.palette[flute_socket.slot];
                const Vec3 local{pal.m[12], pal.m[13], pal.m[14]};
                const Mat4 mm = app.viewer_mode ? Mat4{} : app.player.model_matrix();
                const Vec3 emit{
                    mm.m[0] * local.x + mm.m[4] * local.y + mm.m[8] * local.z + mm.m[12],
                    mm.m[1] * local.x + mm.m[5] * local.y + mm.m[9] * local.z + mm.m[13],
                    mm.m[2] * local.x + mm.m[6] * local.y + mm.m[10] * local.z + mm.m[14]};
                star_timer -= dt_s;
                while (star_timer <= 0.0f) {
                    star_timer += 0.075f;
                    Star s;
                    s.pos = emit + Vec3{(wrand() - 0.5f) * 0.20f, (wrand() - 0.5f) * 0.06f,
                                        (wrand() - 0.5f) * 0.10f};
                    s.vel = Vec3{(wrand() - 0.5f) * 0.22f, 0.05f + wrand() * 0.10f,
                                 -(0.05f + wrand() * 0.10f)};
                    s.max_life = 0.9f + wrand() * 0.7f;
                    s.life = s.max_life;
                    s.size = 0.022f + wrand() * 0.022f;
                    s.spin = wrand() * 6.2831853f;
                    s.spin_rate = (wrand() - 0.5f) * 3.0f;
                    stars.push_back(s);
                }
            }
            star_verts.clear();
            const Vec3 s_eye = app.cam.eye();
            Vec3 s_fwd = normalize(app.cam.target - s_eye);
            Vec3 s_right = normalize(cross(s_fwd, Vec3{0, 1, 0}));
            Vec3 s_up = cross(s_right, s_fwd);
            for (size_t i = 0; i < stars.size();) {
                Star& s = stars[i];
                s.life -= dt_s;
                if (s.life <= 0.0f) {
                    s = stars.back();
                    stars.pop_back();
                    continue;
                }
                s.vel.y -= 0.55f * dt_s;      // gentle fall
                s.vel = s.vel * (1.0f - 0.9f * dt_s);
                s.pos = s.pos + s.vel * dt_s;
                s.spin += s.spin_rate * dt_s;
                const float t = s.life / s.max_life;
                const float alpha = t > 0.75f ? (1.0f - t) * 4.0f : t / 0.75f;
                const float sz = s.size * (0.6f + 0.4f * t);
                const float c = std::cos(s.spin), sn = std::sin(s.spin);
                const Vec3 ax = (s_right * c + s_up * sn) * sz;
                const Vec3 ay = (s_right * -sn + s_up * c) * sz;
                const Vec3 corner[4] = {s.pos - ax - ay, s.pos + ax - ay,
                                        s.pos - ax + ay, s.pos + ax + ay};
                const float uv[4][2] = {{0, 0}, {1, 0}, {0, 1}, {1, 1}};
                const int tri[6] = {0, 1, 2, 2, 1, 3};
                for (const int k : tri) {
                    star_verts.insert(star_verts.end(),
                                      {corner[k].x, corner[k].y, corner[k].z,
                                       uv[k][0], uv[k][1], alpha});
                }
                ++i;
            }
            // (drawn after the character, so his body can't paint over them)
        }

        glUseProgram(skin_prog);
        glUniformMatrix4fv(u_viewproj, 1, GL_FALSE, viewproj.m);
        const Mat4 model_mtx =
            app.viewer_mode ? Mat4{} : app.player.model_matrix();
        glUniformMatrix4fv(u_model, 1, GL_FALSE, model_mtx.m);
        glUniformMatrix4fv(u_palette, static_cast<GLsizei>(app.link.palette.size()),
                           GL_FALSE, app.link.palette.data()->m);
        const Vec3 sun = normalize({-0.4f, -1.0f, -0.35f});
        glUniform3fv(u_sun, 1, &sun.x);
        glUniform1i(u_tex, 0);
        glActiveTexture(GL_TEXTURE0);
        glDisable(GL_CULL_FACE);

        glBindVertexArray(app.link.vao);
        // opaque first, then alpha decals (eyes/brows/mouth)
        for (int pass = 0; pass < 2; ++pass) {
            const bool alpha_pass = pass == 1;
            if (alpha_pass) {
                glEnable(GL_BLEND);
                glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
                glDepthMask(GL_FALSE);
            }
            for (const Submesh& sub : app.link.submeshes) {
                if (sub.alpha_blend != alpha_pass) continue;
                // one eye set or the other: eye.5 (blowing) while on the flute
                if (sub.material == "eye_mat" && blowing) continue;
                if (sub.material == "eye5_mat" && !blowing) continue;
                glBindTexture(GL_TEXTURE_2D, sub.gl_texture);
                glDrawElements(GL_TRIANGLES, static_cast<GLsizei>(sub.index_count),
                               GL_UNSIGNED_INT,
                               reinterpret_cast<void*>(sub.first_index * sizeof(uint32_t)));
            }
            if (alpha_pass) {
                glDisable(GL_BLEND);
                glDepthMask(GL_TRUE);
            }
        }
        glBindVertexArray(0);

        // sparkles last: additive, over the character
        if (!star_verts.empty()) {
            glEnable(GL_BLEND);
            glBlendFunc(GL_SRC_ALPHA, GL_ONE);   // additive: they twinkle
            glDepthMask(GL_FALSE);
            glUseProgram(star_prog);
            glUniformMatrix4fv(s_viewproj, 1, GL_FALSE, viewproj.m);
            glBindVertexArray(star_vao);
            glBindBuffer(GL_ARRAY_BUFFER, star_vbo);
            glBufferData(GL_ARRAY_BUFFER,
                         static_cast<GLsizeiptr>(star_verts.size() * sizeof(float)),
                         star_verts.data(), GL_STREAM_DRAW);
            glDrawArrays(GL_TRIANGLES, 0, static_cast<GLsizei>(star_verts.size() / 6));
            glBindVertexArray(0);
            glDepthMask(GL_TRUE);
            glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
            glDisable(GL_BLEND);
        }

        // --- ocarina sheet-music HUD, fading in while the flute is out ---
        {
            const bool want_hud = !app.viewer_mode &&
                                  app.player.state == PlayerState::Flute;
            if (want_hud != was_fluting) {   // fresh staff each time it opens
                was_fluting = want_hud;
                if (want_hud) {
                    flute_notes.clear();
                    hud_message[0] = '\0';
                }
                song_playing = false;
            }

            // performing a recognised song: the notes land on the staff as
            // they sound, then everything resets so you start over, like OoT
            if (song_playing && song_active) {
                const size_t len = song_active->full_len;
                song_timer += static_cast<float>(frame_dt);
                while (song_index < len &&
                       song_timer >= song_active->full[song_index].t) {
                    const int st = song_active->full[song_index].step;
                    play_note(kScale[st], song_active->full[song_index].vel);
                    if (flute_notes.size() >= 8) flute_notes.clear();  // page turn
                    flute_notes.push_back(st * 4 + 1);
                    ++song_index;
                }
                if (song_index >= len &&
                    song_timer > song_active->full[len - 1].t + 2.2f) {
                    song_playing = false;
                    song_active = nullptr;
                    flute_notes.clear();
                    hud_message[0] = '\0';
                }
            }
            hud_fade += ((want_hud ? 1.0f : 0.0f) - hud_fade) *
                        std::min(1.0f, 7.0f * static_cast<float>(frame_dt));
            if (hud_fade > 0.004f) {
                constexpr float VW = 1280.0f, VH = 720.0f;
                const float F = hud_fade;
                hud_verts.clear();
                auto vtx = [&](float x, float y, const float* c) {
                    hud_verts.insert(hud_verts.end(),
                                     {x, y, c[0], c[1], c[2], c[3] * F});
                };
                auto tri = [&](float x0, float y0, float x1, float y1, float x2,
                               float y2, const float* c) {
                    vtx(x0, y0, c); vtx(x1, y1, c); vtx(x2, y2, c);
                };
                auto rect = [&](float x, float y, float w, float h, const float* c) {
                    tri(x, y, x + w, y, x, y + h, c);
                    tri(x + w, y, x + w, y + h, x, y + h, c);
                };
                auto disc = [&](float cx, float cy, float r, const float* c) {
                    constexpr int N = 20;
                    for (int i = 0; i < N; ++i) {
                        const float a0 = 6.2831853f * i / N;
                        const float a1 = 6.2831853f * (i + 1) / N;
                        tri(cx, cy, cx + r * std::cos(a0), cy + r * std::sin(a0),
                            cx + r * std::cos(a1), cy + r * std::sin(a1), c);
                    }
                };
                auto arc = [&](float cx, float cy, float r, float a0, float a1,
                               const float* c) {
                    constexpr int N = 6;
                    for (int i = 0; i < N; ++i) {
                        const float b0 = a0 + (a1 - a0) * i / N;
                        const float b1 = a0 + (a1 - a0) * (i + 1) / N;
                        tri(cx, cy, cx + r * std::cos(b0), cy + r * std::sin(b0),
                            cx + r * std::cos(b1), cy + r * std::sin(b1), c);
                    }
                };
                // quarter arcs only -- overlapping shapes would double-blend
                // and leave dark blobs at the corners
                auto round_rect = [&](float x, float y, float w, float h, float r,
                                      const float* c) {
                    constexpr float H = 3.14159265f;
                    rect(x + r, y, w - 2 * r, h, c);
                    rect(x, y + r, r, h - 2 * r, c);
                    rect(x + w - r, y + r, r, h - 2 * r, c);
                    arc(x + r, y + r, r, H, 1.5f * H, c);
                    arc(x + w - r, y + r, r, 1.5f * H, 2.0f * H, c);
                    arc(x + r, y + h - r, r, 0.5f * H, H, c);
                    arc(x + w - r, y + h - r, r, 0.0f, 0.5f * H, c);
                };
                auto seg = [&](float x0, float y0, float x1, float y1, float th,
                               const float* c) {
                    float dx = x1 - x0, dy = y1 - y0;
                    const float len = std::sqrt(dx * dx + dy * dy);
                    if (len < 1e-5f) return;
                    dx /= len; dy /= len;
                    const float nx = -dy * th * 0.5f, ny = dx * th * 0.5f;
                    tri(x0 + nx, y0 + ny, x1 + nx, y1 + ny, x0 - nx, y0 - ny, c);
                    tri(x1 + nx, y1 + ny, x1 - nx, y1 - ny, x0 - nx, y0 - ny, c);
                };
                auto glyph = [&](char ch, float x, float y, float px,
                                 const float* c) {
                    if (ch >= 'a' && ch <= 'z') ch = static_cast<char>(ch - 32);
                    for (const Glyph& g : kFont) {
                        if (g.c != ch) continue;
                        for (int cx = 0; cx < 5; ++cx)
                            for (int ry = 0; ry < 7; ++ry)
                                if (g.col[cx] & (1 << ry))
                                    rect(x + cx * px, y + ry * px, px, px, c);
                        return;
                    }
                };
                auto text = [&](const char* s, float x, float y, float px,
                                const float* c) {
                    for (const char* p = s; *p; ++p) {
                        glyph(*p, x, y, px, c);
                        x += 6 * px;
                    }
                    return x;
                };
                auto text_w = [](const char* s, float px) {
                    return static_cast<float>(std::strlen(s)) * 6.0f * px;
                };

                auto ellipse = [&](float cx, float cy, float rx, float ry,
                                   float tilt, const float* c) {
                    constexpr int N = 18;
                    const float ct = std::cos(tilt), st = std::sin(tilt);
                    for (int i = 0; i < N; ++i) {
                        const float a0 = 6.2831853f * i / N;
                        const float a1 = 6.2831853f * (i + 1) / N;
                        const float x0 = rx * std::cos(a0), y0 = ry * std::sin(a0);
                        const float x1 = rx * std::cos(a1), y1 = ry * std::sin(a1);
                        tri(cx, cy, cx + x0 * ct - y0 * st, cy + x0 * st + y0 * ct,
                            cx + x1 * ct - y1 * st, cy + x1 * st + y1 * ct, c);
                    }
                };

                const float panel_c[4] = {0.05f, 0.04f, 0.06f, 0.88f};
                const float edge_c[4] = {0.55f, 0.42f, 0.20f, 0.75f};
                const float staff_c[4] = {0.98f, 0.42f, 0.13f, 1.0f};
                const float cream[4] = {0.97f, 0.94f, 0.88f, 1.0f};
                const float white[4] = {0.96f, 0.96f, 0.94f, 1.0f};

                const bool has_msg = hud_message[0] != '\0';
                const float PH = has_msg ? 156.0f : 126.0f;
                const float PX = 340.0f, PY = 690.0f - PH, PW = 600.0f;
                round_rect(PX - 2, PY - 2, PW + 4, PH + 4, 16, edge_c);
                round_rect(PX, PY, PW, PH, 15, panel_c);

                if (has_msg) {
                    const float px = 2.0f;
                    const float x = PX + (PW - text_w(hud_message, px)) * 0.5f;
                    text(hud_message, x, PY + 16, px, white);
                }

                // staff: five orange lines, like the ocarina UI
                const float SX = PX + 24, SW = PW - 48;
                const float SGAP = 17.0f;
                const float S0 = PY + (has_msg ? 52.0f : 26.0f);
                for (int i = 0; i < 5; ++i)
                    rect(SX, S0 + i * SGAP, SW, 2.4f, staff_c);
                const float bottom_line = S0 + 4 * SGAP;

                // the notes he has played, as real notation: the natural sits on
                // its line or space, with the accidental drawn beside it
                for (size_t i = 0; i < flute_notes.size(); ++i) {
                    const int step = flute_notes[i] / 4;        // 0=C .. 7=C'
                    const int acc = flute_notes[i] % 4 - 1;     // -1 flat, +1 sharp
                    const float nx = SX + 96 + i * 52.0f;
                    const float ny = bottom_line - step * (SGAP * 0.5f);
                    const float rx = SGAP * 0.60f, ry = SGAP * 0.42f;
                    ellipse(nx, ny, rx + 1.2f, ry + 1.2f, -0.32f, staff_c);
                    ellipse(nx, ny, rx, ry, -0.32f, cream);
                    // stem: up on the right for low notes, down on the left high up
                    if (step < 4)
                        rect(nx + rx - 2.4f, ny - 3.1f * SGAP, 2.6f, 3.1f * SGAP, cream);
                    else
                        rect(nx - rx, ny, 2.6f, 3.1f * SGAP, cream);
                    if (acc != 0)
                        glyph(acc > 0 ? '#' : 'b', nx - rx - 13.0f, ny - 7.0f, 2.0f,
                              cream);
                }

                glDisable(GL_DEPTH_TEST);
                glEnable(GL_BLEND);
                glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
                glUseProgram(hud_prog);
                const float screen_uni[3] = {VW, VH, 0.0f};
                glUniform3fv(h_screen, 1, screen_uni);
                glBindVertexArray(hud_vao);
                glBindBuffer(GL_ARRAY_BUFFER, hud_vbo);
                glBufferData(GL_ARRAY_BUFFER,
                             static_cast<GLsizeiptr>(hud_verts.size() * sizeof(float)),
                             hud_verts.data(), GL_STREAM_DRAW);
                glDrawArrays(GL_TRIANGLES, 0,
                             static_cast<GLsizei>(hud_verts.size() / 6));
                glBindVertexArray(0);

                // the real clef glyph, as a tinted alpha quad
                {
                    const float ch = 7.4f * SGAP;
                    const float cw = ch * kClefW / static_cast<float>(kClefH);
                    const float cx0 = SX + 8.0f;
                    // the spiral of the glyph sits ~63% down: line it up with G
                    const float cy0 = (S0 + 3 * SGAP) - 0.63f * ch;
                    const float quad[6][4] = {
                        {cx0, cy0, 0, 0},
                        {cx0 + cw, cy0, 1, 0},
                        {cx0, cy0 + ch, 0, 1},
                        {cx0 + cw, cy0, 1, 0},
                        {cx0 + cw, cy0 + ch, 1, 1},
                        {cx0, cy0 + ch, 0, 1},
                    };
                    const float clef_col[4] = {0.98f, 0.74f, 0.24f, F};
                    glUseProgram(clef_prog);
                    glUniform3fv(ct_screen, 1, screen_uni);
                    glUniform4fv(ct_color, 1, clef_col);
                    glUniform1i(ct_tex, 0);
                    glActiveTexture(GL_TEXTURE0);
                    glBindTexture(GL_TEXTURE_2D, clef_tex);
                    glBindVertexArray(clef_vao);
                    glBindBuffer(GL_ARRAY_BUFFER, clef_vbo);
                    glBufferData(GL_ARRAY_BUFFER, sizeof(quad), quad, GL_STREAM_DRAW);
                    glDrawArrays(GL_TRIANGLES, 0, 6);
                    glBindVertexArray(0);
                }
                glDisable(GL_BLEND);
                glEnable(GL_DEPTH_TEST);
            }
        }

        if (want_shot || shot_path) {
            save_screenshot(shot_path ? shot_path : "screenshot.bmp", fb_w, fb_h);
            want_shot = false;
            if (shot_path) app.running = false;
        }

        SDL_GL_SwapWindow(app.window);

        ++fps_frames;
        if (now_ns - fps_last_ns >= 1'000'000'000ull) {
            set_title(app, fps_frames);
            fps_frames = 0;
            fps_last_ns = now_ns;
        }
    }

    SDL_GL_DestroyContext(app.gl);
    SDL_DestroyWindow(app.window);
    SDL_Quit();
    return 0;
}
